### PR TITLE
Smaller images

### PR DESCRIPTION
**Pull request by colearendt**
remove R .deb/.rpm files
remove apt cache from layers

### CODE REVIEW

**Comment by koverholt** [comment]
I'd like to remove the commands to `rm -rf /var/lib/apt/lists/*` since it can cause problems with later installations or commands that users might add (and it appears to be breaking the CI build). Users can always customize these images and add these optimizations, so I'd like to keep these images as a simple starting point as much as possible.

We can definitely leave the commands to clean up the RPMs for R, thanks for catching that.

**Comment by colearendt** [comment]
Oops @koverholt I hadn't removed the `rm -rf /var/lib/apt/lists/*` yet. Do you want me to fix that?

**Comment by colearendt** [comment]
One thing worth considering for discussion about whether removing the apt cache is valuable. Even if it is included, we get this after time elapses:

```
E: Failed to fetch http://security.ubuntu.com/ubuntu/pool/main/v/vim/xxd_8.0.1453-1ubuntu1.1_amd64.deb  404  Not Found [IP: 91.189.88.152 80]
E: Failed to fetch http://security.ubuntu.com/ubuntu/pool/main/v/vim/vim-common_8.0.1453-1ubuntu1.1_all.deb  404  Not Found [IP: 91.189.88.152 80]
E: Failed to fetch http://security.ubuntu.com/ubuntu/pool/main/v/vim/vim-runtime_8.0.1453-1ubuntu1.1_all.deb  404  Not Found [IP: 91.189.88.152 80]
E: Failed to fetch http://security.ubuntu.com/ubuntu/pool/main/v/vim/vim_8.0.1453-1ubuntu1.1_amd64.deb  404  Not Found [IP: 91.189.88.152 80]
E: Unable to fetch some archives, maybe run apt-get update or try with --fix-missing?
```

And an `apt-get update` is still necessary. It would be better in my opinion if we remove the cache at each layer and just document that `apt-get update` is necessary any time you want to use `apt` / `gdebi`. A bad cache in the layer above a layer you are trying to change can be problematic too - another benefit for being explicit about the caching.

**Comment by koverholt** [comment]
Ah apologies, I thought that latest commit was your fix since CI was passing. Feel free to continue in another PR!

**Comment by colearendt** [comment]
@koverholt thoughts on my message above? Leaving the cache around gives you intermittent failures like the above based on cache age. In practice, `apt-get update` is always required to make `apt`/`gdebi` functional in a docker image. 

_Should_ I follow up with a PR to remove the cache removal? My inclination is just to explain that `apt-get update` is always required to make things functional for extending.

**Comment by koverholt** [comment]
So at the moment we `apt-get update` before every call to `apt`, and we remove cache afterwards? If so, this is consistent with what we do in the CentOS image and we can leave it as is... assuming my understanding is correct.

**Comment by colearendt** [comment]
Yes, exactly. The only (maybe noteworthy) difference is that you also have to `apt-get update` before and remove cache after any call to `gdebi` as well. There has been some dev discussion around moving from `gdebi` to `apt` in the future because `apt` can now resolve dependencies for local files. So maybe we'll get there someday soon 😄

**Comment by rstub** [comment]
I think it is expected behavior for any Debain/Ubuntu derived image to *not* include the cache, making `apt update` necessary.

**Pull request merged**
