### PR TITLE
Bump RSP version to 1.4.1103-1

### PR DESCRIPTION
**Pull request by dfalty**
I've updated the version. Let me know if we need to change the url for centos here. I wasn't sure! https://github.com/rstudio/docker-r-session-complete/blob/master/r-session-complete/centos7/.env#L2

### CODE REVIEW

**Comment by colearendt** [comment]
Yeah, I definitely think we do! @dfalty Sorry for the delay on this. That concerns me that we might be building invalid centos images... need to add some testing to verify this... although... is there a way to verify that the session bits run properly?

**Comment by dfalty** [comment]
Unfortunately, I don't think there is a way to specifically test the sessions bits outside of RSP with `verify-installation --verify-user`.

**Comment by dfalty** [comment]
@colearendt Alright, update url

**Comment by dfalty** [comment]
@colearendt I can't see the error so I don't know why centos7 is still failing. Let me know if there is anything I can do!

**Comment by colearendt** [comment]
Fixed, I think - the platform changed from centos6 -> centos7

**Review by colearendt — APPROVED** [review]
LGTM!

**Pull request merged**
