### PR TITLE
Update to 3.8.1 code-server

### PR DESCRIPTION
**Pull request by dfalty**

### CODE REVIEW

**Comment by colearendt** [comment]
@dfalty Nice on the `--strip-components`! It's probably worth highlighting that this was a breaking change. We might ought to think about how to notify users (maybe a `NEWS.md`)? 

Further, it's good cause to highlight https://github.com/rstudio/rstudio-pro/issues/1692 (but for vscode) so that these types of things are not breaking changes.

**Comment by colearendt** [comment]
I.e. (example NEWS entry)

- BREAKING: Changed code-server version and insulated against version upgrades in the future. To update:

change:
_vscode.conf_
```
enabled=1
exe=/opt/code-server/code-server-3.2.0-linux-x86_64/code-server
```

to:
_vscode.conf_
```
enabled=1
exe=/opt/code-server/code-server
```

**Comment by dfalty** [comment]
Oh right, that makes sense. I should have waited to merge I was just working on testing something out so I rushed it :/

**Comment by colearendt** [comment]
No worries! It is a change that I think we needed to make eventually, so definitely valid! It may be worth us keeping in mind that having our dev images built and accessible somewhere could be useful (for integration testing before releases / etc.).

**Comment by colearendt** [comment]
Does code-server 3.8.1 work with RSP 1.4 as released? That's probably something worth making sure

**Comment by dfalty** [comment]
@colearendt code-server 3.8.1 does work with the new RSP 1.4-juliet-rose release that is coming up. We now default to installing 3.8.1 when running `sudo rstudio-server install-vs-code` https://github.com/rstudio/rstudio-pro/pull/2335 
We have some more full tests to run against the version but base functionality works good on Local Launcher 1.4.1620-1 + 3.8.1. We should probably match the version automatically installed by RSP. https://github.com/rstudio/rstudio-pro/blob/fe09f68c8d02499812b0ba6aeea187d90170731d/src/cpp/server/extras/scripts/install-vs-code#L51-L54 What do you think?

**Comment by colearendt** [comment]
Yeah, that's a good call. Do we document these version compatibilities anywhere? I feel like we should to create an ideal workflow for those building their own images (i.e. if RSP session bits are not already installed)

**Pull request merged**
